// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: icademo/txdemo/zone.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Zone struct {
	// Chain ID of the host zone
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Bech32 prefix of host zone's address
	Bech32Prefix string `protobuf:"bytes,17,opt,name=bech32prefix,proto3" json:"bech32prefix,omitempty"`
	// ConnectionID to the host zone
	ConnectionId string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// Transfer Channel ID to the host zone
	TransferChannelId string `protobuf:"bytes,3,opt,name=transfer_channel_id,json=transferChannelId,proto3" json:"transfer_channel_id,omitempty"`
	// ibc denom of the host zone's native token
	IbcDenom string `protobuf:"bytes,4,opt,name=ibc_denom,json=ibcDenom,proto3" json:"ibc_denom,omitempty"`
	// native denom on host zone
	HostDenom string `protobuf:"bytes,5,opt,name=host_denom,json=hostDenom,proto3" json:"host_denom,omitempty"`
	// The unbonding period in days (e.g. 21)
	UnbondingPeriod uint64 `protobuf:"varint,6,opt,name=unbonding_period,json=unbondingPeriod,proto3" json:"unbonding_period,omitempty"`
	// List of validators that are delegated to
	Validators []*Validator `protobuf:"bytes,7,rep,name=validators,proto3" json:"validators,omitempty"`
	// Address that custodies native tokens during a liquid stake
	DepositAddress string `protobuf:"bytes,8,opt,name=deposit_address,json=depositAddress,proto3" json:"deposit_address,omitempty"`
	// ICA Address on the host zone responsible for staking and unstaking
	DelegationIcaAddress string `protobuf:"bytes,9,opt,name=delegation_ica_address,json=delegationIcaAddress,proto3" json:"delegation_ica_address,omitempty"`
	// ICA Address on the host zone responsible for collecting rewards
	WithdrawalIcaAddress string `protobuf:"bytes,10,opt,name=withdrawal_ica_address,json=withdrawalIcaAddress,proto3" json:"withdrawal_ica_address,omitempty"`
	// ICA Address that receives unstaked tokens after they've finished unbonding
	RedemptionIcaAddress string `protobuf:"bytes,11,opt,name=redemption_ica_address,json=redemptionIcaAddress,proto3" json:"redemption_ica_address,omitempty"`
}

func (m *Zone) Reset()         { *m = Zone{} }
func (m *Zone) String() string { return proto.CompactTextString(m) }
func (*Zone) ProtoMessage()    {}
func (*Zone) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cb3055bf94467ae, []int{0}
}
func (m *Zone) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Zone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Zone.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Zone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Zone.Merge(m, src)
}
func (m *Zone) XXX_Size() int {
	return m.Size()
}
func (m *Zone) XXX_DiscardUnknown() {
	xxx_messageInfo_Zone.DiscardUnknown(m)
}

var xxx_messageInfo_Zone proto.InternalMessageInfo

func (m *Zone) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *Zone) GetBech32Prefix() string {
	if m != nil {
		return m.Bech32Prefix
	}
	return ""
}

func (m *Zone) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *Zone) GetTransferChannelId() string {
	if m != nil {
		return m.TransferChannelId
	}
	return ""
}

func (m *Zone) GetIbcDenom() string {
	if m != nil {
		return m.IbcDenom
	}
	return ""
}

func (m *Zone) GetHostDenom() string {
	if m != nil {
		return m.HostDenom
	}
	return ""
}

func (m *Zone) GetUnbondingPeriod() uint64 {
	if m != nil {
		return m.UnbondingPeriod
	}
	return 0
}

func (m *Zone) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *Zone) GetDepositAddress() string {
	if m != nil {
		return m.DepositAddress
	}
	return ""
}

func (m *Zone) GetDelegationIcaAddress() string {
	if m != nil {
		return m.DelegationIcaAddress
	}
	return ""
}

func (m *Zone) GetWithdrawalIcaAddress() string {
	if m != nil {
		return m.WithdrawalIcaAddress
	}
	return ""
}

func (m *Zone) GetRedemptionIcaAddress() string {
	if m != nil {
		return m.RedemptionIcaAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*Zone)(nil), "icademo.txdemo.Zone")
}

func init() { proto.RegisterFile("icademo/txdemo/zone.proto", fileDescriptor_8cb3055bf94467ae) }

var fileDescriptor_8cb3055bf94467ae = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x6e, 0xd3, 0x30,
	0x1c, 0xc6, 0x1b, 0x56, 0xb6, 0xd6, 0x83, 0x8d, 0x99, 0x0a, 0xa5, 0x43, 0x44, 0xd5, 0xb8, 0x14,
	0x09, 0x12, 0x69, 0x3b, 0x71, 0xdc, 0x40, 0x48, 0xbd, 0x4c, 0xa8, 0x20, 0x0e, 0xbb, 0x44, 0x8e,
	0xed, 0x26, 0x96, 0x12, 0xff, 0x23, 0xdb, 0x65, 0x1d, 0x4f, 0xc1, 0xc3, 0xf0, 0x10, 0x1c, 0x27,
	0x4e, 0x1c, 0x51, 0xfb, 0x00, 0xbc, 0x02, 0x8a, 0x9d, 0x34, 0x2b, 0x3b, 0xf4, 0xd4, 0xfe, 0xbf,
	0xdf, 0xf7, 0x7d, 0xb1, 0xec, 0x3f, 0x1a, 0x0a, 0x4a, 0x18, 0x2f, 0x20, 0x32, 0x0b, 0xfb, 0xf3,
	0x0d, 0x24, 0x0f, 0x4b, 0x05, 0x06, 0xf0, 0x41, 0x8d, 0x42, 0x87, 0x8e, 0x07, 0x29, 0xa4, 0x60,
	0x51, 0x54, 0xfd, 0x73, 0xae, 0xe3, 0x61, 0x0a, 0x90, 0xe6, 0x3c, 0xb2, 0x53, 0x32, 0x9f, 0x45,
	0x44, 0xde, 0x34, 0x88, 0x82, 0x2e, 0x40, 0xc7, 0x2e, 0xe3, 0x86, 0x1a, 0x05, 0xff, 0x7d, 0xf6,
	0x2b, 0xc9, 0x05, 0x23, 0x06, 0x94, 0xe3, 0x27, 0x7f, 0xbb, 0xa8, 0x7b, 0x05, 0x92, 0xe3, 0x21,
	0xea, 0xd1, 0x8c, 0x08, 0x19, 0x0b, 0xe6, 0x7b, 0x23, 0x6f, 0xdc, 0x9f, 0xee, 0xd9, 0x79, 0xc2,
	0xf0, 0x09, 0x7a, 0x94, 0x70, 0x9a, 0x9d, 0x9d, 0x96, 0x8a, 0xcf, 0xc4, 0xc2, 0x3f, 0xb2, 0x78,
	0x43, 0xc3, 0x2f, 0xd1, 0x63, 0x0a, 0x52, 0x72, 0x6a, 0x04, 0xd8, 0x8e, 0x07, 0xce, 0xd4, 0x8a,
	0x13, 0x86, 0x43, 0xf4, 0xd4, 0x28, 0x22, 0xf5, 0x8c, 0xab, 0x98, 0x66, 0x44, 0x4a, 0x9e, 0x57,
	0xd6, 0x1d, 0x6b, 0x3d, 0x6a, 0xd0, 0x3b, 0x47, 0x26, 0x0c, 0x3f, 0x47, 0x7d, 0x91, 0xd0, 0x98,
	0x71, 0x09, 0x85, 0xdf, 0xb5, 0xae, 0x9e, 0x48, 0xe8, 0xfb, 0x6a, 0xc6, 0x2f, 0x10, 0xca, 0x40,
	0x9b, 0x9a, 0x3e, 0xb4, 0xb4, 0x5f, 0x29, 0x0e, 0xbf, 0x42, 0x4f, 0xe6, 0x32, 0x01, 0xc9, 0x84,
	0x4c, 0xe3, 0x92, 0x2b, 0x01, 0xcc, 0xdf, 0x1d, 0x79, 0xe3, 0xee, 0xf4, 0x70, 0xad, 0x7f, 0xb4,
	0x32, 0x7e, 0x8b, 0xd0, 0xfa, 0x5a, 0xb4, 0xbf, 0x37, 0xda, 0x19, 0xef, 0x9f, 0x0e, 0xc3, 0xcd,
	0x47, 0x09, 0xbf, 0x34, 0x8e, 0xe9, 0x1d, 0x33, 0x3e, 0x47, 0x87, 0x8c, 0x97, 0xa0, 0x85, 0x89,
	0x09, 0x63, 0x8a, 0x6b, 0xed, 0xf7, 0xaa, 0x93, 0x5c, 0xf8, 0xbf, 0x7e, 0xbc, 0x19, 0xd4, 0x2f,
	0x71, 0xee, 0xc8, 0x27, 0xa3, 0x84, 0x4c, 0xa7, 0x07, 0x75, 0xa0, 0x56, 0xf1, 0x25, 0x7a, 0xc6,
	0x78, 0xce, 0x53, 0xe2, 0x6e, 0x8e, 0x92, 0x75, 0x53, 0x7f, 0x4b, 0xd3, 0xa0, 0xcd, 0x4d, 0x28,
	0xb9, 0xd3, 0x77, 0x2d, 0x4c, 0xc6, 0x14, 0xb9, 0x26, 0xf9, 0x46, 0x1f, 0xda, 0xd6, 0xd7, 0xe6,
	0x36, 0xfb, 0x14, 0x67, 0xbc, 0x28, 0xef, 0x9d, 0x6f, 0x7f, 0x5b, 0x5f, 0x9b, 0x6b, 0xfb, 0x2e,
	0x3e, 0xfc, 0x5c, 0x06, 0xde, 0xed, 0x32, 0xf0, 0xfe, 0x2c, 0x03, 0xef, 0xfb, 0x2a, 0xe8, 0xdc,
	0xae, 0x82, 0xce, 0xef, 0x55, 0xd0, 0xb9, 0x7a, 0x9d, 0x0a, 0x93, 0xcd, 0x93, 0x90, 0x42, 0x11,
	0x7d, 0xce, 0x88, 0xcc, 0x2e, 0xab, 0x4d, 0x88, 0x9a, 0x0d, 0x5e, 0x34, 0x3b, 0x6c, 0x6e, 0x4a,
	0xae, 0x93, 0x5d, 0xbb, 0xc0, 0x67, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x6c, 0x01, 0x4e,
	0x59, 0x03, 0x00, 0x00,
}

func (m *Zone) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Zone) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Zone) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Bech32Prefix) > 0 {
		i -= len(m.Bech32Prefix)
		copy(dAtA[i:], m.Bech32Prefix)
		i = encodeVarintZone(dAtA, i, uint64(len(m.Bech32Prefix)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if len(m.RedemptionIcaAddress) > 0 {
		i -= len(m.RedemptionIcaAddress)
		copy(dAtA[i:], m.RedemptionIcaAddress)
		i = encodeVarintZone(dAtA, i, uint64(len(m.RedemptionIcaAddress)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.WithdrawalIcaAddress) > 0 {
		i -= len(m.WithdrawalIcaAddress)
		copy(dAtA[i:], m.WithdrawalIcaAddress)
		i = encodeVarintZone(dAtA, i, uint64(len(m.WithdrawalIcaAddress)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.DelegationIcaAddress) > 0 {
		i -= len(m.DelegationIcaAddress)
		copy(dAtA[i:], m.DelegationIcaAddress)
		i = encodeVarintZone(dAtA, i, uint64(len(m.DelegationIcaAddress)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.DepositAddress) > 0 {
		i -= len(m.DepositAddress)
		copy(dAtA[i:], m.DepositAddress)
		i = encodeVarintZone(dAtA, i, uint64(len(m.DepositAddress)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Validators) > 0 {
		for iNdEx := len(m.Validators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Validators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintZone(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.UnbondingPeriod != 0 {
		i = encodeVarintZone(dAtA, i, uint64(m.UnbondingPeriod))
		i--
		dAtA[i] = 0x30
	}
	if len(m.HostDenom) > 0 {
		i -= len(m.HostDenom)
		copy(dAtA[i:], m.HostDenom)
		i = encodeVarintZone(dAtA, i, uint64(len(m.HostDenom)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.IbcDenom) > 0 {
		i -= len(m.IbcDenom)
		copy(dAtA[i:], m.IbcDenom)
		i = encodeVarintZone(dAtA, i, uint64(len(m.IbcDenom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TransferChannelId) > 0 {
		i -= len(m.TransferChannelId)
		copy(dAtA[i:], m.TransferChannelId)
		i = encodeVarintZone(dAtA, i, uint64(len(m.TransferChannelId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ConnectionId) > 0 {
		i -= len(m.ConnectionId)
		copy(dAtA[i:], m.ConnectionId)
		i = encodeVarintZone(dAtA, i, uint64(len(m.ConnectionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintZone(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintZone(dAtA []byte, offset int, v uint64) int {
	offset -= sovZone(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Zone) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovZone(uint64(l))
	}
	l = len(m.ConnectionId)
	if l > 0 {
		n += 1 + l + sovZone(uint64(l))
	}
	l = len(m.TransferChannelId)
	if l > 0 {
		n += 1 + l + sovZone(uint64(l))
	}
	l = len(m.IbcDenom)
	if l > 0 {
		n += 1 + l + sovZone(uint64(l))
	}
	l = len(m.HostDenom)
	if l > 0 {
		n += 1 + l + sovZone(uint64(l))
	}
	if m.UnbondingPeriod != 0 {
		n += 1 + sovZone(uint64(m.UnbondingPeriod))
	}
	if len(m.Validators) > 0 {
		for _, e := range m.Validators {
			l = e.Size()
			n += 1 + l + sovZone(uint64(l))
		}
	}
	l = len(m.DepositAddress)
	if l > 0 {
		n += 1 + l + sovZone(uint64(l))
	}
	l = len(m.DelegationIcaAddress)
	if l > 0 {
		n += 1 + l + sovZone(uint64(l))
	}
	l = len(m.WithdrawalIcaAddress)
	if l > 0 {
		n += 1 + l + sovZone(uint64(l))
	}
	l = len(m.RedemptionIcaAddress)
	if l > 0 {
		n += 1 + l + sovZone(uint64(l))
	}
	l = len(m.Bech32Prefix)
	if l > 0 {
		n += 2 + l + sovZone(uint64(l))
	}
	return n
}

func sovZone(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozZone(x uint64) (n int) {
	return sovZone(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Zone) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowZone
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Zone: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Zone: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZone
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZone
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZone
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZone
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZone
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZone
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZone
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZone
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZone
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransferChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZone
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZone
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZone
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZone
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZone
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZone
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingPeriod", wireType)
			}
			m.UnbondingPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZone
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZone
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZone
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZone
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validators = append(m.Validators, &Validator{})
			if err := m.Validators[len(m.Validators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZone
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZone
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZone
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationIcaAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZone
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZone
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZone
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegationIcaAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalIcaAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZone
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZone
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZone
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawalIcaAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedemptionIcaAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZone
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZone
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZone
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RedemptionIcaAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bech32Prefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZone
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZone
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZone
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bech32Prefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipZone(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthZone
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipZone(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowZone
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowZone
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowZone
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthZone
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupZone
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthZone
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthZone        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowZone          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupZone = fmt.Errorf("proto: unexpected end of group")
)
